name: Verify codegen script

on: 
  push:
    paths:
      - 'testscript.sh'
      - 'markdown_table_codegen.py'
jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Verify markdown_table_codegen.py script
        run: ./tools/testscript.sh
        shell: bash
