name: Verify codegen script

on: 
  push:
    paths: 
      - 'tools/markdown_table_codegen.py'
  workflow_dispatch:

jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Verify markdown_table_codegen.py script
        run: ./tools/testscript.sh
        shell: bash
