on: 
  push:
    paths: 
      - 'markdown_table_codegen.py'
jobs:
  verify-codegen:
    steps:
      - name: Verify markdown_table_codegen.py script
        run: ./tools/testscript.sh
        shell: bash
